### ISSUE TITLE
False positives (app install/text messages...)

### ISSUE THREAD

**Issue by MaxMuehlbronner** [nikolamilosevic86/owasp-seraphimdroid#26]
When Seraphimdroid receives a text message / SMS it will always report it as malicious if there are numbers in the message. I think there should be a feature to whitelist some numbers, maybe it would make sense to just don't report messages sent by your contacts? For example: Nagios text messages are always flagged as potentially malicious...

Also for any app being installed or updated, it will always report it as potentially malicious app install.

**Comment by nikolamilosevic86** [comment]
Hello MaxMuehlbronner,

Thank you for reporting a bug. Regarding text message improvement suggestion, I completely agree. I will have a look and try to improve it, unless you want to get involved and try to fix it yourself? I would welcome further contributions by you (code, testing, documenting, marketing, whatever you feel like doing).

For the updating/installing, I think, currently when something is updated/installed, it checks all the apps and fires notification if on your phone has at least one potentially malicious app. Can you check this?

**Comment by MaxMuehlbronner** [comment]
Hi,

thanks for your prompt reply, yes i would really like to contribute in 
some way. I have been an OWASP member for some time but did not 
contribute in any way yet. We will see how much i am able to support 
you, I think seraphimdroid could be a great aid in the protection of 
android users like myself. ;)

In the permission scanner every app shows a Green symbol which i thought 
means it is not potentially malicious (maybe i have misinterpreted the 
green for OK?)

But on every app update or new installed app (via google play or manual 
.apk installation (unknown sources)) it always says "the application you 
installed may be malicious".



Best Regards


Max M.

**Comment by thewayofknowing** [comment]
The issue regarding false positive notification for app install was realized post pushing the update to playstore. I believe the repo has the updated code.

**Comment by nikolamilosevic86** [comment]
I have updated the newest version you sent @thewayofknowing to Google Play, so either you compiled it without it, or there is a bug. Anyway this should be checked and if the case is that there are notification when all apps are green, that is bug. 

@MaxMuehlbronner Thank you for showing enthusiasm. I believe the good start would be to join mailing list (you already are here and know how to use bug tracking system). It would be good if you can indroduce yourself on the mailing list (https://lists.owasp.org/mailman/listinfo/owasp_seraphimdroid_project) and tell us about your skills or what you would like to do on project. And we can discuss general things there and keep this discussion over the reported issue.

**Comment by thewayofknowing** [comment]
I realized the bug sometime later, when I was using it. I fixed it and pushed the updated code to repo

**Comment by nikolamilosevic86** [comment]
Right, are you still able to compile and send it to me, so I can update Google Play?

**Comment by nikolamilosevic86** [comment]
I have just checked the code. It seems it is indeed fixed. I have created new version and published on Google play. @MaxMuehlbronner can you check when you get update whether it really works, or the bug persists?

**Comment by MaxMuehlbronner** [comment]
Confirmed, there is no notification anymore (when updating apps via google play). And the Incoming text messages are not flagged as malicious. So everything is working fine for me now. :)
